name: SubscriberCheck
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          python check_and_update.py ${{ secrets.YOUTUBE_CHANNEL_ID }} ${{ secrets.YOUTUBE_API_KEY }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          if [[ `git status --porcelain` ]]; then
            commitmessage="Data updated on $(date +%Y%m%d)"
            git add subscriber_count.txt
            git add view_count.txt          
            git commit -m "${commitmessage}"
            git push
          fi